### ISSUE TITLE
[BUG] Rank points are not saving

### ISSUE THREAD

**Issue by Kepapi** [K4ryuu/K4-System#168] opened 2024-04-12 14:18 UTC
Rank points are not saving, rolls back after map change.

For example if on map start i have 1020 points, ill get some points during map and before map changes i have 1100 points. After map changes my points will go back to 1020.

**Comment by flipper1923** [comment] 2024-04-13 09:56
!top comand dont work well !

**Comment by K4ryuu** [comment] 2024-04-13 19:39
@Kepapi I have tested this problem with 4.1.2 and I'm unable to reproduce it. Probably you have used 4.1.0 or 4.1.1, which had that problem. I would like to ask you to check this problem of your's again with the latest version that I'm going to upload now.

**Comment by K4ryuu** [comment] 2024-04-14 19:48
The problem has been fixed in the latest release.
Thank you!

**Closed as completed by K4ryuu** 2024-04-14 19:48 UTC
Labels: Bug, Priority: Medium
