### ISSUE TITLE
[ENHANCEMENT] Let players to select if they want rank tags in tab & add chat tags for ranks

### ISSUE THREAD

**Issue by pandathebeasty** [K4ryuu/K4-System#156] opened 2024-03-25 09:10 UTC
- [ ] Let each player to select if they want to have rank tags & score in tab, something like toggletags for permissions.
- [ ] Add chat tags for each rank

**Comment by K4ryuu** [comment] 2024-03-26 11:51
The rank tags and so can be managed by the server owner. I think for a server that is using rank system it's unnecessary to let the people toggle them. The server owner decides if they want to show them for everyone or now. Permissions based tags are a different story, since admins likes to vanish.

The other is is just a duplicate of #99 

I close this issue as a wontfix for now. The first feature seems like just a junk into the code for me, so first you should vote it with people on my [Discord Server](https://discord.gg/gs2s4xHfeh) to be added.

Best Regards,
K4ryuu

**Closed as not planned by K4ryuu** 2024-03-26 11:51 UTC
Labels: Priority: Low, Enhancement
