### ISSUE TITLE
[FEATURE] Hide Messegaes in chat.

### ISSUE THREAD

**Issue by zOdet** [K4ryuu/K4-System#150] opened 2024-03-12 08:39 UTC
Add a way to hide all:
# All RanksPoints messages
# Experience gain messages

Adding this feature will help with distraction during a match. 
Ex, if you have the plugin on a scrim server.

**Comment by K4ryuu** [comment] 2024-03-16 11:48
This is a duplicate of #145. I'm closing this.

**Closed as not planned by K4ryuu** 2024-03-16 11:48 UTC
Labels: Feature Request, Priority: Low
